---
######################
### Cisco Switches ###
######################
 - hosts: cisco_switches
   gather_facts: no
   connection: local

   tasks:
     - name: Collect configuration from all switches
       ios_command:
         commands: show run

       register: RUNCFG

     - name: define time format
       set_fact: time="{{lookup('pipe','date \"+%Y-%m-%d\"')}}"

     - name: save output to a file
       connection: local
       copy:
         content="\n ===show run=== \n {{ RUNCFG.stdout[0] }}"
         dest="/var/backups/switch/{{ inventory_hostname }}_run_cfg_{{ time }}.txt"

######################
### Cisco Switches ###
######################
 - hosts: juniper_routers
   gather_facts: no
   connection: local

   tasks:
     - name: configurable backup path
       junos_config:
         src: srx.cfg
         backup: yes
         backup_options:
           filename: backup.cfg
           dir_path: /var/backups/router 
