#use ansible-playbook install-nginx.yml -K  for run become root
---
- name: Configure webserver with nginx
  hosts: testservers
  sudo: True
  tasks:
      - name: install nginx
        apt: name=nginx update_cache=yes
    
      #- name: copy nginx config file
      #  copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

      #- name: enable configuration
      #  file: >
      #    dest=/etc/nginx/sites-enabled/default
      #    src=/etc/nginx/sites-available/default
      #    state=link

      - name: copy index.html
        template: src=/var/ansible/playbooks/index.html dest=/usr/share/nginx/html/index.html
          mode=0644

      - name: restart nginx
        service: name=nginx state=restarted
