---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Make sure that we can connect to the machine
      ping:
    - name: Install PHP
      apt: name=php state=present update_cache=yes
